import { auth } from "@/auth";
import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { Comfortaa } from "next/font/google";
import "./globals.css";

const font_base = Comfortaa({
  weight: ["400", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font_base",
});

export const metadata: Metadata = {
  title: "Jeferson Santos",
  // description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <SessionProvider session={session}>
      <html lang="pt-BR">
        <body className={font_base.className}>{children}</body>
      </html>
    </SessionProvider>
  );
}
